### ISSUE TITLE
Tpa code

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#17]
I'm pretty sure I can code the plugin so that 

<PlayerA> tpto player
message: "playerA wants to TPA to you. type '.tpaccept <playerA>' to allow it.
<player> .tpaccept playerA
""Whoosh..."

However, I want to place a time limit after which the "offer" expires.

**Comment by M4GNV5** [comment]
For writing the main functionalities so that players can ask other players for teleports you can just add playerA to an associative array like `myAssArray[playerB] = playerA;` Then if playerB accepts the teleport get the playername from the associative array, teleport player A to B and then remove player A from the array by doing e.g. `myAssArray[playerName] = false;` or delete the whole entry with `delete myAssArray[playerName];` (see [the MDN reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete) for more information about the delete keyword)

for expiring the offer you can use the javascript Date class (see the [MDN Page](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date) about it) actually its quite simple just add a new date object to another (or the same) associative array like anotherAssArray[playerB] = new Date(); and when the other person accepts use [getTime()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) to get the time when playerA asked for the teleport in milliseconds and subtract it from the current time `new Time().getTime()` to get the difference between ask and accept time in milliseconds

I didnt want to give you source code on how to do this because it would be like giving hungry people fish instead if a fishing rod :wink:

**Comment by suresttexas00** [comment]
I appreciate it because I do want to write it myself...

```
                  =
```

**Comment by M4GNV5** [comment]
well then:

``` javascript
const tpAskExpire = 60000; //1minute = 1 * 60 * 1000 milliseconds

var tpRequests = {};
var tpTimestamps = {};
function ChatReceived(name, message)
{
    var args = message.split(' ');
    var command = standertize(args[0]);
    if(command  == '.tpask')
    {
        var other = standertize(args[1]);
        tpRequests[other] = name;
        tpTimestamps[other] = new Date().getTime();
    }
    else if(command  == '.tpaccept' && tpRequests[name])
    {
        var currentTime = new Date().getTime();
        if((currentTime - tpTimestamps[name]) > tpAskExpire)
        {
            Player.SendMessageTo(name, "Expired!", "red");
        }
        else
        {
            var other = tpRequests[name];
            Player.SendMessageTo(other, "Teleport accepted", "green");
            Server.RunCommand("tp "+other+" "+name);
        }
        delete tpRequests[name];
        delete tpTimestamps[name];
    }
}
function standertize(text)
{
    text = text || "";
    return text.trim().toLowerCase() || "";
}
```

I havent tested it though
