### ISSUE TITLE
Last game session

### ISSUE THREAD

**Issue by suresttexas00** [M4GNV5/NINSS#6]
The last game session today ended with the NINSS exe file crashing, due to:

An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll

Additional information: startIndex cannot be larger than length of string.

System.ArgumentOutOfRangeException was unhandled
Message: An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Additional information: startIndex cannot be larger than length of string.

not sure if this was caused by something in the plugin or additional error checking it should have done... This is the only bit of plugin code I added that might have errored out (if you pressed 't' for chat, but then pressed enter with nothing)

if (args[0].slice(0,1) == ".")
            {
            Player.SendMessageTo(name, "Command not was recognized.  Type .help", "red");
            Console.WriteLine("[Simple] Player " + name + " attemped ." + args[0] + ", which is not a valid command");
            return;
            }
This snippet runs in ChatReceived after all the other .<whatever> commands and after the CAPS check.  So you would not have been able to get on after this, as I was out and could not restart the console.

**Comment by suresttexas00** [comment]
OK, I take that back... the server Jar is still running sans window as a background process... a problem for me because I have 4 other worlds running.  I guess I must OP myself after all!.. so I can go into the game and run the stop command.  So, you would have been able to keep playing but no NINSS...

**Comment by M4GNV5** [comment]
I need the stacktrace...
If its just an event error in a Plugin it should say something like "... Stacktrace: <stacktrace"
Otherwise NINSS crashes and it should tell you the stacktrace just in the console
Note: if your console is just closing (because NINSS crashes) open a commandline `windows+r`->`cmd`->`enter` type in `cd Path/To/NINSS` and then `./NINSS.exe`

Yeah I know if NINSS crashes but the Minecraft server doesnt you need to open the taskmanager (windows) to kill the minecraft server process...
Alternativly if you are running on a system with GUI (so basically  every windows) just remove the "nogui" from the java arguments in the NINSS.xml file and it will open the normal Minecraft server GUI where you still can type in "stop" to stop the server

**Comment by M4GNV5** [comment]
Actually i think i know what the problem was so i added a security check for incoming data from the minecraft server: https://github.com/M4GNV5/NINSS/commit/ee21ddce5b72870c35dd788afc05f54ea252dc66

**Comment by suresttexas00** [comment]
I also had the plugin check for empty string..
